name: flutter_terrabayt_app
description: Terrabaytni flutterda qilingan appi.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^4.1.2+1
  dio: ^3.0.10
  get_it: ^5.0.3
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  cached_network_image: ^2.5.0
  webview_flutter: ^1.0.7

flutter:
  uses-material-design: true

  assets:
    - assets/