name: flutter_terrabayt_app
description: Terrabaytni flutterda qilingan appi.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^3.1.0
  google_fonts: ^1.1.1
  dio: ^3.0.10
  get_it: ^5.0.3
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  cached_network_image: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/